-- Consolidated Migration for Adaptabuddy
-- Generated by Gemini
-- Based on P02 series prompts

BEGIN;

-- 1. Extensions & Helpers
create extension if not exists "pgcrypto"; -- often useful

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- 2. Tables

-- users
create table if not exists public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  units_pref text not null default 'lbs' check (units_pref in ('lbs','kg')),
  unit_conversion float8 not null default 2.2046226218, -- lbs per kg
  bodyweight float8,
  sex text not null default 'male' check (sex in ('male','female')),
  injuries jsonb not null default '[]'::jsonb,
  preferences jsonb not null default '{}'::jsonb,
  active_program_json jsonb not null default '{}'::jsonb,
  active_program_version int not null default 1,
  offline_sync_cursor bigint not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- muscle_groups
create table if not exists public.muscle_groups (
  id bigserial primary key,
  name text not null unique,
  slug text not null unique,
  region text not null, -- Upper, Lower, Core
  parent_id bigint references muscle_groups(id),
  created_at timestamptz default now()
);

-- muscle_groups slug normalization (for legacy rows)
alter table public.muscle_groups add column if not exists slug text;
update public.muscle_groups
set slug = lower(regexp_replace(trim(name), '\s+', '-', 'g'))
where slug is null;
create unique index if not exists uq_muscle_groups_slug on public.muscle_groups(slug);
alter table public.muscle_groups alter column slug set not null;

-- exercises
create table if not exists public.exercises (
  id bigserial primary key,
  canonical_name text not null unique,
  aliases text[] not null default '{}'::text[],
  movement_pattern text not null,
  equipment text[] not null default '{}'::text[],
  is_bodyweight boolean default false,
  primary_muscle_group_id bigint references muscle_groups(id),
  secondary_muscle_group_ids bigint[] not null default '{}'::bigint[],
  tags text[] not null default '{}'::text[],
  contraindications jsonb not null default '[]'::jsonb,
  default_warmups jsonb not null default '[]'::jsonb,
  default_warmdowns jsonb not null default '[]'::jsonb,
  media jsonb not null default '{}'::jsonb, -- {image_url, video_url}
  created_at timestamptz default now()
);

-- templates
create table if not exists public.templates (
  id bigserial primary key,
  name text not null,
  disciplines text[] not null default '{}'::text[],
  methodology text,
  version int not null default 1,
  template_json jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  unique (name, version)
);

-- training_sessions
create table if not exists public.training_sessions (
  id bigserial primary key,
  user_id uuid references users(user_id) on delete cascade,
  session_date date not null,
  program_session_key text not null,
  status text check (status in ('planned','completed','missed','skipped')) default 'planned',
  reschedule_flag boolean default false,
  inconsistency_score int default 0,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, session_date, program_session_key)
);

-- training_exercises
create table if not exists public.training_exercises (
  id bigserial primary key,
  session_id bigint references training_sessions(id) on delete cascade,
  exercise_id bigint references exercises(id),
  exercise_key text not null,
  name text not null, -- snapshot of name
  tags text[] not null default '{}'::text[],
  movement_pattern text,
  primary_muscle_group_id bigint references muscle_groups(id),
  secondary_muscle_group_ids bigint[] not null default '{}'::bigint[],
  is_completed boolean default false,
  pain_score int check (pain_score is null or (pain_score >= 0 and pain_score <= 10)),
  order_index int not null default 0
);

-- training_sets
create table if not exists public.training_sets (
  id bigserial primary key,
  exercise_id bigint references training_exercises(id) on delete cascade,
  set_index int not null,
  reps int,
  weight float8,
  rpe float8 check (rpe is null or (rpe >= 0 and rpe <= 10)),
  rir float8 check (rir is null or (rir >= 0 and rir <= 10)),
  tempo text,
  rest_seconds int,
  is_amrap boolean default false,
  is_joker boolean default false,
  created_at timestamptz default now(),
  unique (exercise_id, set_index)
);

-- push_subscriptions
create table if not exists public.push_subscriptions (
  id bigserial primary key,
  user_id uuid references users(user_id) on delete cascade,
  subscription jsonb not null,
  created_at timestamptz default now(),
  unique (user_id)
);

-- sync_events
create table if not exists public.sync_events (
  id bigserial primary key,
  user_id uuid references users(user_id) on delete cascade,
  event_id uuid not null,
  local_seq bigint not null,
  ts timestamptz not null,
  type text not null,
  payload jsonb not null,
  created_at timestamptz default now(),
  unique (user_id, event_id),
  unique (user_id, local_seq)
);

-- 3. Indexes
create index if not exists idx_training_sessions_user_date on public.training_sessions (user_id, session_date);
create index if not exists idx_training_exercises_session on public.training_exercises (session_id);
create index if not exists idx_training_sets_exercise on public.training_sets (exercise_id);
create index if not exists idx_sync_events_user_seq on public.sync_events (user_id, local_seq);
-- Unique constraints covered by table definitions above.

-- 4. Triggers
drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at before update on public.users for each row execute procedure public.set_updated_at();

drop trigger if exists set_training_sessions_updated_at on public.training_sessions;
create trigger set_training_sessions_updated_at before update on public.training_sessions for each row execute procedure public.set_updated_at(); 

-- 5. RLS Enablement
alter table public.users enable row level security;
alter table public.training_sessions enable row level security;
alter table public.training_exercises enable row level security;
alter table public.training_sets enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.sync_events enable row level security;
alter table public.muscle_groups enable row level security;
alter table public.exercises enable row level security;
alter table public.templates enable row level security;

alter table public.users force row level security;
alter table public.training_sessions force row level security;
alter table public.training_exercises force row level security;
alter table public.training_sets force row level security;
alter table public.push_subscriptions force row level security;
alter table public.sync_events force row level security;
alter table public.muscle_groups force row level security;
alter table public.exercises force row level security;
alter table public.templates force row level security;

-- 6. Policies

-- USERS
create policy "Users: Select own" on public.users for select using (user_id = auth.uid());
create policy "Users: Insert own" on public.users for insert with check (user_id = auth.uid());
create policy "Users: Update own" on public.users for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users: Delete own" on public.users for delete using (user_id = auth.uid());
create policy "Users: Service role all" on public.users for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- TRAINING SESSIONS
create policy "Sessions: Select own" on public.training_sessions for select using (user_id = auth.uid());
create policy "Sessions: Insert own" on public.training_sessions for insert with check (user_id = auth.uid());
create policy "Sessions: Update own" on public.training_sessions for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Sessions: Delete own" on public.training_sessions for delete using (user_id = auth.uid());
create policy "Sessions: Service role all" on public.training_sessions for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- TRAINING EXERCISES
-- (Using simpler EXISTS logic)
create policy "Exercises: Select own" on public.training_exercises for select using (
  exists (select 1 from public.training_sessions ts where ts.id = session_id and ts.user_id = auth.uid())
);
create policy "Exercises: Insert own" on public.training_exercises for insert with check (
  exists (select 1 from public.training_sessions ts where ts.id = session_id and ts.user_id = auth.uid())
);
create policy "Exercises: Update own" on public.training_exercises for update using (
  exists (select 1 from public.training_sessions ts where ts.id = session_id and ts.user_id = auth.uid())
) with check (
  exists (select 1 from public.training_sessions ts where ts.id = session_id and ts.user_id = auth.uid())
);
create policy "Exercises: Delete own" on public.training_exercises for delete using (
  exists (select 1 from public.training_sessions ts where ts.id = session_id and ts.user_id = auth.uid())
);
create policy "Exercises: Service role all" on public.training_exercises for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- TRAINING SETS
create policy "Sets: Select own" on public.training_sets for select using (
  exists (
    select 1 from public.training_exercises te 
    join public.training_sessions ts on ts.id = te.session_id 
    where te.id = exercise_id and ts.user_id = auth.uid()
  )
);
create policy "Sets: Insert own" on public.training_sets for insert with check (
  exists (
    select 1 from public.training_exercises te 
    join public.training_sessions ts on ts.id = te.session_id 
    where te.id = exercise_id and ts.user_id = auth.uid()
  )
);
create policy "Sets: Update own" on public.training_sets for update using (
  exists (
    select 1 from public.training_exercises te 
    join public.training_sessions ts on ts.id = te.session_id 
    where te.id = exercise_id and ts.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.training_exercises te 
    join public.training_sessions ts on ts.id = te.session_id 
    where te.id = exercise_id and ts.user_id = auth.uid()
  )
);
create policy "Sets: Delete own" on public.training_sets for delete using (
  exists (
    select 1 from public.training_exercises te 
    join public.training_sessions ts on ts.id = te.session_id 
    where te.id = exercise_id and ts.user_id = auth.uid()
  )
);
create policy "Sets: Service role all" on public.training_sets for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- PUSH SUBSCRIPTIONS
create policy "Push: Select own" on public.push_subscriptions for select using (user_id = auth.uid());
create policy "Push: Insert own" on public.push_subscriptions for insert with check (user_id = auth.uid());
create policy "Push: Update own" on public.push_subscriptions for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Push: Delete own" on public.push_subscriptions for delete using (user_id = auth.uid());
create policy "Push: Service role all" on public.push_subscriptions for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- SYNC EVENTS
create policy "Sync: Select own" on public.sync_events for select using (user_id = auth.uid());
create policy "Sync: Insert own" on public.sync_events for insert with check (user_id = auth.uid());
create policy "Sync: Update own" on public.sync_events for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Sync: Delete own" on public.sync_events for delete using (user_id = auth.uid());
create policy "Sync: Service role all" on public.sync_events for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- LIBRARY (Read-only for users, writable by service role)
-- Muscle Groups
create policy "MG: Read all" on public.muscle_groups for select using (auth.role() in ('authenticated','service_role'));
create policy "MG: Service role write" on public.muscle_groups for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- Exercises
create policy "Exercises: Read all" on public.exercises for select using (auth.role() in ('authenticated','service_role'));
create policy "Exercises: Service role write" on public.exercises for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- Templates
create policy "Templates: Read all" on public.templates for select using (auth.role() in ('authenticated','service_role'));
create policy "Templates: Service role write" on public.templates for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

COMMIT;
